services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/vishalsaini0822/scrollx
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://scrollxtest.onrender.com/
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mydbhost.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: my_laravel_db
      - key: DB_USERNAME
        value: myuser
      - key: DB_PASSWORD
        value: mypassword
