<?php
require_once 'vendor/autoload.php';

// Simple test for Windows Media Player compatibility
echo "Creating a very basic MP4 that Windows Media Player should accept...\n";

// Create the most minimal MP4 structure possible
$mp4Data = '';

// ftyp box (file type) - tell Windows this is an MP4
$ftypData = 'mp42' . pack('N', 0) . 'mp42isom';
$mp4Data .= pack('N', 8 + strlen($ftypData)) . 'ftyp' . $ftypData;

// Simple mdat box with minimal "video" content
$mdatData = "SCROLLX.IO VIDEO FILE\n\nThis is a test video generated by ScrollX.io\n";
$mdatData .= "Project: Test Video\n";
$mdatData .= "Resolution: 1280x720\n";
$mdatData .= "Duration: 10 seconds\n";
$mdatData .= str_repeat("Frame data simulation...\n", 50);

$mp4Data .= pack('N', 8 + strlen($mdatData)) . 'mdat' . $mdatData;

// Write to file
$testFile = 'test_simple.mp4';
file_put_contents($testFile, $mp4Data);

echo "✅ Simple MP4 created: $testFile\n";
echo "File size: " . filesize($testFile) . " bytes\n";

// Check structure
$handle = fopen($testFile, 'rb');
$header = fread($handle, 32);
fclose($handle);

if (strpos($header, 'ftyp') !== false) {
    echo "✅ File type box found\n";
}
if (strpos($header, 'mp42') !== false) {
    echo "✅ MP4 brand found\n";
}

echo "\nTry opening this file in Windows Media Player: $testFile\n";
